(() => {
  const $ = id => document.getElementById(id); let data = ShiftStorage.load(); let viewDate = new Date(); let overrideDate = null;
  const monthTitle=$('monthTitle'), grid=$('calendarGrid'), todayCard=$('todayCard'), legend=$('legend');
  const fmt = date => `${date.getFullYear()}년 ${date.getMonth()+1}월`; const todayKey=()=>ShiftEngine.key(new Date());
  function renderToday(){ const shift=ShiftEngine.shiftFor(new Date(),data.settings,data.overrides); todayCard.innerHTML=`<div class="today-label">오늘 · ${new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'})}</div><div class="today-shift">${shift.name}</div><div class="today-meta">${ShiftEngine.timeRange(shift)}${data.overrides[todayKey()] !== undefined ? ' · 날짜별 변경' : ''}</div>`; }
  function renderLegend(){ const p=ShiftEngine.PATTERNS[data.settings.pattern]; const seen=new Set(); legend.innerHTML=''; p.types.forEach((t,i)=>{if(seen.has(t[0]))return;seen.add(t[0]); const el=document.createElement('span');el.className='legend-item';el.innerHTML=`<i class="legend-dot" style="background:${t[1]}"></i>${t[0]}`;legend.append(el);}); }
  function renderCalendar(){ monthTitle.textContent=fmt(viewDate); grid.innerHTML=''; const first=new Date(viewDate.getFullYear(),viewDate.getMonth(),1); const start=new Date(viewDate.getFullYear(),viewDate.getMonth(),1-first.getDay()); for(let i=0;i<42;i++){const date=new Date(start);date.setDate(start.getDate()+i);const key=ShiftEngine.key(date),shift=ShiftEngine.shiftFor(date,data.settings,data.overrides),cell=document.createElement('button');cell.className='day-cell';if(date.getMonth()!==viewDate.getMonth())cell.classList.add('muted');if(date.getDay()===0)cell.classList.add('sunday');if(date.getDay()===6)cell.classList.add('saturday');if(key===todayKey())cell.classList.add('today');cell.setAttribute('aria-label',`${key} ${shift.name}${data.notes[key]?' 메모 있음':''}`);cell.innerHTML=`<span class="day-number">${date.getDate()}</span><span class="shift-pill ${shift.isOff?'off':''}" style="background:${shift.color}">${shift.name}</span>${data.overrides[key]!==undefined?'<i class="override-dot"></i>':''}${data.notes[key]?'<i class="note-dot" title="메모 있음"></i>':''}`;cell.addEventListener('click',()=>openOverride(date));grid.append(cell);}}
  function render(){renderToday();renderCalendar();renderLegend();}
  function populateSettings(){const select=$('patternSelect');select.innerHTML='';Object.entries(ShiftEngine.PATTERNS).forEach(([key,p])=>{const o=document.createElement('option');o.value=key;o.textContent=p.name;select.append(o);});select.value=data.settings.pattern; $('anchorDate').value=data.settings.anchorDate;populateAnchorOptions();}
  function populateAnchorOptions(){const p=ShiftEngine.PATTERNS[$('patternSelect').value];const select=$('anchorIndex');select.innerHTML='';p.types.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}일차 · ${t[0]}${t[6]?'':' · '+ShiftEngine.timeRange(ShiftEngine.shiftFor(new Date(2000,0,1),{pattern:$('patternSelect').value,anchorDate:'2000-01-01',anchorIndex:i},{}))}`;select.append(o);});select.value=String(data.settings.anchorIndex);}
  function openSettings(){populateSettings();$('settingsDialog').showModal();}
  function openOverride(date){overrideDate=date;const p=ShiftEngine.PATTERNS[data.settings.pattern];$('overrideTitle').textContent=`${date.getMonth()+1}월 ${date.getDate()}일 근무 변경`;const select=$('overrideSelect');select.innerHTML='';p.types.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}일차 · ${t[0]}`;select.append(o);});const key=ShiftEngine.key(date);select.value=String(data.overrides[key] ?? ((data.settings.anchorIndex+Math.round((date-new Date(data.settings.anchorDate+'T00:00:00'))/86400000))%p.types.length+p.types.length)%p.types.length);$('noteInput').value=data.notes[key] || '';$('overrideDialog').showModal();}
  $('previousMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);renderCalendar();};$('nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar();};$('todayButton').onclick=()=>{viewDate=new Date();render();};$('settingsButton').onclick=openSettings;$('patternSelect').onchange=populateAnchorOptions;
  $('settingsForm').addEventListener('submit',e=>{if(e.submitter?.id!=='saveSettings')return;data.settings={pattern:$('patternSelect').value,anchorDate:$('anchorDate').value,anchorIndex:Number($('anchorIndex').value)};data.overrides={};ShiftStorage.save(data);render();});
  $('overrideForm').addEventListener('submit',e=>{if(e.submitter?.id!=='saveOverride'||!overrideDate)return;const key=ShiftEngine.key(overrideDate);data.overrides[key]=Number($('overrideSelect').value);const note=$('noteInput').value.trim();if(note)data.notes[key]=note;else delete data.notes[key];ShiftStorage.save(data);render();});$('clearOverride').onclick=()=>{if(!overrideDate)return;delete data.overrides[ShiftEngine.key(overrideDate)];ShiftStorage.save(data);$('overrideDialog').close();render();};$('exportButton').onclick=()=>ShiftStorage.exportData(data);$('importInput').onchange=e=>{if(e.target.files[0])ShiftStorage.importData(e.target.files[0],next=>{data=next;populateSettings();render();$('settingsDialog').close();});};
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{}); render();
})();
